import { Career } from './supabase'

export const careersData: Career[] = [
  // GOVERNMENT JOBS - Administrative / Civil Services
  {
    id: 'ias-officer',
    name: 'IAS Officer',
    sector: 'Government',
    category: 'Civil Services',
    education: 'Any Graduate',
    age_limit: '21-32 years',
    selection_process: 'UPSC CSE (Prelims → Mains → Interview)',
    conducting_body: 'UPSC',
    salary_range: '₹56,100 - ₹2,50,000',
    job_description: 'Indian Administrative Service officers are the administrative head of districts, implementing government policies, managing revenue, law & order, and development activities.',
    key_skills: ['Leadership', 'Decision Making', 'Public Administration', 'Communication', 'Critical Thinking', 'Law Knowledge'],
    work_location: 'Pan India',
    job_nature: 'Field + Office',
    growth_prospects: 'SDM → DM/Collector → Commissioner → Secretary → Chief Secretary → Cabinet Secretary',
    perks_benefits: 'Government bungalow, car with driver, medical, pension, LTC, security, prestige',
    ai_risk_percentage: 35,
    competition_ratio: '1:5,556',
    exam_id: 'upsc-cse',
    exam_name: 'UPSC Civil Services Exam'
  },
  {
    id: 'ips-officer',
    name: 'IPS Officer',
    sector: 'Government',
    category: 'Civil Services',
    education: 'Any Graduate',
    age_limit: '21-32 years',
    selection_process: 'UPSC CSE (Prelims → Mains → Interview)',
    conducting_body: 'UPSC',
    salary_range: '₹56,100 - ₹2,25,000',
    job_description: 'Indian Police Service officers maintain law and order, combat crime, and manage police forces at district, state, and national levels.',
    key_skills: ['Leadership', 'Law', 'Crisis Management', 'Investigation', 'Communication', 'Physical Fitness'],
    work_location: 'Pan India',
    job_nature: 'Field + Office',
    growth_prospects: 'DSP → SP → DIG → IG → ADGP → DGP',
    perks_benefits: 'Government accommodation, vehicle, armed protection, pension, prestige',
    ai_risk_percentage: 25,
    competition_ratio: '1:5,000',
    exam_id: 'upsc-cse',
    exam_name: 'UPSC Civil Services Exam'
  },
  {
    id: 'ifs-officer',
    name: 'IFS Officer',
    sector: 'Government',
    category: 'Civil Services',
    education: 'Any Graduate',
    age_limit: '21-32 years',
    selection_process: 'UPSC CSE (Prelims → Mains → Interview)',
    conducting_body: 'UPSC',
    salary_range: '₹56,100 - ₹2,25,000',
    job_description: 'Indian Forest Service officers manage forests, wildlife, and environment. They balance conservation with development.',
    key_skills: ['Ecology', 'Forest Law', 'Wildlife Management', 'Administration', 'Leadership'],
    work_location: 'Forest Areas / Wildlife Sanctuaries / National Parks',
    job_nature: 'Field + Office',
    growth_prospects: 'ACF → DFO → Conservator → CCF → PCCF',
    perks_benefits: 'Forest bungalow, vehicle, pension, prestige',
    ai_risk_percentage: 20,
    competition_ratio: '1:20,000',
    exam_id: 'upsc-cse',
    exam_name: 'UPSC Civil Services Exam'
  },
  {
    id: 'irs-officer',
    name: 'IRS Officer',
    sector: 'Government',
    category: 'Civil Services',
    education: 'Any Graduate',
    age_limit: '21-32 years',
    selection_process: 'UPSC CSE (Prelims → Mains → Interview)',
    conducting_body: 'UPSC',
    salary_range: '₹56,100 - ₹2,00,000',
    job_description: 'Indian Revenue Service officers handle direct and indirect taxes, enforcement, and revenue collection for the government.',
    key_skills: ['Taxation Law', 'Accounting', 'Investigation', 'Legal Knowledge', 'Analytical Skills'],
    work_location: 'Pan India',
    job_nature: 'Office + Field',
    growth_prospects: 'ACIT → DCIT → JCIT → CIT → CCIT → Pr. CCIT',
    perks_benefits: 'Government accommodation, vehicle, pension, medical',
    ai_risk_percentage: 40,
    competition_ratio: '1:12,500',
    exam_id: 'upsc-cse',
    exam_name: 'UPSC Civil Services Exam'
  },
  // State Administration
  {
    id: 'sdm-tehsildar',
    name: 'SDM / Tehsildar',
    sector: 'Government',
    category: 'State Administration',
    education: 'Graduate',
    age_limit: '18-40 years (varies by state)',
    selection_process: 'State PCS Exam (Prelims → Mains → Interview)',
    conducting_body: 'State PSC',
    salary_range: '₹35,000 - ₹1,20,000',
    job_description: 'Sub-Divisional Magistrates and Tehsildars handle revenue administration, land records, and local governance at sub-divisional level.',
    key_skills: ['Revenue Law', 'Land Records', 'Public Administration', 'Communication'],
    work_location: 'State-specific postings',
    job_nature: 'Field + Office',
    growth_prospects: 'Tehsildar → SDM → ADM → DM',
    perks_benefits: 'Government quarters, vehicle, pension, job security',
    ai_risk_percentage: 30,
    competition_ratio: '1:500',
    exam_id: 'state-pcs',
    exam_name: 'State PCS Exam'
  },
  // Defence
  {
    id: 'indian-army-officer',
    name: 'Indian Army Officer',
    sector: 'Government',
    category: 'Defence',
    education: 'Graduate (NDA for 10+2)',
    age_limit: '16.5-27 years',
    selection_process: 'NDA Exam / CDS Exam / SSB Interview',
    conducting_body: 'UPSCs',
    salary_range: '₹56,100 - ₹2,50,000 + MSP',
    job_description: 'Army officers lead soldiers in various operations, manage logistics, and handle strategic planning at multiple levels.',
    key_skills: ['Leadership', 'Physical Fitness', 'Tactical Planning', 'Weapons Handling', 'Team Management'],
    work_location: 'Pan India + Field Postings',
    job_nature: 'Field',
    growth_prospects: 'Lieutenant → Captain → Major → Lt. Colonel → Colonel → Brigadier → Major General → Lt. General → General',
    perks_benefits: 'Army accommodation, ration, uniform, pension, ECHS medical, canteen, LTC',
    ai_risk_percentage: 15,
    competition_ratio: '1:500',
    exam_id: 'nda',
    exam_name: 'NDA Exam'
  },
  {
    id: 'indian-navy-officer',
    name: 'Indian Navy Officer',
    sector: 'Government',
    category: 'Defence',
    education: 'Engineering Graduate / 10+2 PCM (NDA)',
    age_limit: '16.5-27 years',
    selection_process: 'NDA / CDS / INET / SSB Interview',
    conducting_body: 'Indian Navy',
    salary_range: '₹56,100 - ₹2,50,000 + MSP',
    job_description: 'Navy officers operate warships, submarines, and aircraft. They handle naval operations, navigation, and maritime security.',
    key_skills: ['Naval Operations', 'Navigation', 'Engineering', 'Leadership', 'Physical Fitness'],
    work_location: 'Coastal bases + Sea Deployment',
    job_nature: 'Sea + Base',
    growth_prospects: 'Sub Lieutenant → Lieutenant → Lt. Commander → Commander → Captain → Commodore → Vice Admiral → Admiral',
    perks_benefits: 'Naval accommodation, ration, pension, ECHS, sea pay allowance',
    ai_risk_percentage: 15,
    competition_ratio: '1:600',
    exam_id: 'nda',
    exam_name: 'NDA Exam'
  },
  {
    id: 'indian-airforce-officer',
    name: 'Air Force Officer',
    sector: 'Government',
    category: 'Defence',
    education: '12th PCM / Engineering Graduate',
    age_limit: '16.5-26 years',
    selection_process: 'NDA / AFCAT / CDSE / SSB Interview',
    conducting_body: 'Indian Air Force',
    salary_range: '₹56,100 - ₹2,50,000 + Flying Allowance',
    job_description: 'Air Force officers fly aircraft, manage air operations, handle technical systems, and provide air support during conflicts.',
    key_skills: ['Flying Skills', 'Aviation Technology', 'Physics', 'Leadership', 'Decision Making Under Pressure'],
    work_location: 'Air Force Bases Pan India',
    job_nature: 'Air + Base',
    growth_prospects: 'Flying Officer → Flight Lieutenant → Squadron Leader → Wing Commander → Group Captain → Air Marshal → CAS',
    perks_benefits: 'AF accommodation, flying allowance, pension, ECHS, canteen',
    ai_risk_percentage: 18,
    competition_ratio: '1:700',
    exam_id: 'afcat',
    exam_name: 'AFCAT'
  },
  {
    id: 'army-soldier',
    name: 'Army Soldier (Agniveer)',
    sector: 'Government',
    category: 'Defence',
    education: '10th Pass / 12th Pass',
    age_limit: '17.5-23 years',
    selection_process: 'Agnipath Scheme / Rally Bharti / Physical + Medical',
    conducting_body: 'Indian Army',
    salary_range: '₹30,000 - ₹60,000',
    job_description: 'Soldiers serve in various roles including infantry, technical trades, and support functions during their 4-year Agniveer tenure.',
    key_skills: ['Physical Fitness', 'Discipline', 'Weapons Handling', 'Team Coordination'],
    work_location: 'Pan India + Field Postings',
    job_nature: 'Field',
    growth_prospects: 'Sepoy → Naik → Havildar → Naib Subedar → Subedar → Subedar Major',
    perks_benefits: 'Ration, uniform, accommodation, canteen, ex-serviceman benefits, Seva Nidhi',
    ai_risk_percentage: 20,
    competition_ratio: '1:100',
    exam_id: null,
    exam_name: null
  },
  // Police
  {
    id: 'sub-inspector',
    name: 'Sub-Inspector (State Police)',
    sector: 'Government',
    category: 'Police',
    education: 'Graduate',
    age_limit: '20-28 years',
    selection_process: 'State Police SI Exam (Written + Physical + Medical + Interview)',
    conducting_body: 'State Police',
    salary_range: '₹35,400 - ₹1,12,400',
    job_description: 'SIs investigate crimes, maintain law and order, supervise constables, and assist senior officers in police operations.',
    key_skills: ['Investigation', 'Law', 'Communication', 'Physical Fitness', 'Leadership'],
    work_location: 'State-specific',
    job_nature: 'Field + Office',
    growth_prospects: 'Constable → Head Constable → ASI → SI → Inspector → DSP',
    perks_benefits: 'Government quarters, pension, uniform allowance, medical',
    ai_risk_percentage: 28,
    competition_ratio: '1:200',
    exam_id: 'state-police-si',
    exam_name: 'State Police SI Exam'
  },
  {
    id: 'police-constable',
    name: 'Police Constable',
    sector: 'Government',
    category: 'Police',
    education: '10+2',
    age_limit: '18-25 years',
    selection_process: 'Written Test + Physical Efficiency Test + Medical Exam',
    conducting_body: 'State Police',
    salary_range: '₹21,700 - ₹69,100',
    job_description: 'Constables are the backbone of police force, handling beat duties, patrol, law enforcement, and assisting in investigations.',
    key_skills: ['Physical Fitness', 'Discipline', 'Basic Legal Knowledge', 'Communication'],
    work_location: 'State-specific',
    job_nature: 'Field',
    growth_prospects: 'Constable → Head Constable → ASI → SI',
    perks_benefits: 'Pension, uniform, accommodation (some states), medical',
    ai_risk_percentage: 35,
    competition_ratio: '1:150',
    exam_id: 'state-police-constable',
    exam_name: 'State Police Constable Exam'
  },
  {
    id: 'crpf-constable',
    name: 'CRPF Constable',
    sector: 'Government',
    category: 'Paramilitary',
    education: '10th Pass',
    age_limit: '18-23 years',
    selection_process: 'SSC GD Exam (CBT + PET + Medical)',
    conducting_body: 'SSC',
    salary_range: '₹21,700 - ₹69,100',
    job_description: 'CRPF personnel assist state police in internal security, counter-insurgency, and law enforcement operations.',
    key_skills: ['Physical Fitness', 'Weapons Handling', 'Discipline', 'Security Operations'],
    work_location: 'Pan India / Border Areas',
    job_nature: 'Field',
    growth_prospects: 'Constable → Head Constable → ASI → SI → Inspector',
    perks_benefits: 'Accommodation, ration, pension, canteen, uniform allowance',
    ai_risk_percentage: 25,
    competition_ratio: '1:100',
    exam_id: 'ssc-gd',
    exam_name: 'SSC GD Constable'
  },
  // Railways
  {
    id: 'railway-je',
    name: 'Railway Junior Engineer',
    sector: 'Government',
    category: 'Railways',
    education: 'Diploma/B.Tech in relevant branch',
    age_limit: '18-36 years',
    selection_process: 'RRB JE Exam (CBT 1 + CBT 2 + Document Verification)',
    conducting_body: 'RRB',
    salary_range: '₹35,400 - ₹1,12,400',
    job_description: 'JEs handle technical aspects of railway operations including civil, electrical, mechanical, and signaling engineering.',
    key_skills: ['Engineering', 'Supervision', 'Safety Compliance', 'Project Management'],
    work_location: 'Pan India Railway Zones',
    job_nature: 'Field + Office',
    growth_prospects: 'JE → SE → XEN → Sr. XEN → DRM',
    perks_benefits: 'Quarters, pension, medical, TA/DA, free rail pass',
    ai_risk_percentage: 45,
    competition_ratio: '1:170',
    exam_id: 'rrb-je',
    exam_name: 'RRB Junior Engineer Exam'
  },
  {
    id: 'loco-pilot',
    name: 'Railway Loco Pilot',
    sector: 'Government',
    category: 'Railways',
    education: '10th Pass + ITI / 12th Pass + Diploma',
    age_limit: '18-28 years',
    selection_process: 'RRB ALP Exam (CBT 1 + CBT 2 + CBAT + Medical)',
    conducting_body: 'RRB',
    salary_range: '₹19,900 - ₹63,200',
    job_description: 'Loco Pilots operate trains, ensuring safe and timely transportation of passengers and goods across railway networks.',
    key_skills: ['Technical Knowledge', 'Alertness', 'Concentration', 'Physical & Mental Fitness'],
    work_location: 'Across Railway Zones',
    job_nature: 'On-board',
    growth_prospects: 'ALP → Senior ALP → Loco Pilot (Goods) → Loco Pilot (Mail/Express) → Loco Pilot (Passenger)',
    perks_benefits: 'Free rail pass, quarters, pension, REHS medical, uniform',
    ai_risk_percentage: 55,
    competition_ratio: '1:250',
    exam_id: 'rrb-alp',
    exam_name: 'RRB ALP Exam'
  },
  {
    id: 'station-master',
    name: 'Station Master',
    sector: 'Government',
    category: 'Railways',
    education: 'Graduate',
    age_limit: '18-33 years',
    selection_process: 'RRB NTPC Exam (CBT 1 + CBT 2 + Skill Test)',
    conducting_body: 'RRB',
    salary_range: '₹35,400 - ₹1,12,400',
    job_description: 'Station Masters manage train operations at stations, ensuring safety, scheduling, and passenger services.',
    key_skills: ['Communication', 'Decision Making', 'Railway Operations', 'Alertness'],
    work_location: 'Across Railway Zones',
    job_nature: 'Shift-based Office',
    growth_prospects: 'ASM → SM → Chief SM → Inspector of Stations',
    perks_benefits: 'Free rail pass, quarters, pension, REHS medical, uniform',
    ai_risk_percentage: 40,
    competition_ratio: '1:370',
    exam_id: 'rrb-ntpc',
    exam_name: 'RRB NTPC Exam'
  },
  // Banking
  {
    id: 'bank-po',
    name: 'Bank Probationary Officer',
    sector: 'Government',
    category: 'Banking',
    education: 'Graduate',
    age_limit: '20-30 years',
    selection_process: 'IBPS/SBI PO Exam (Prelims + Mains + Interview)',
    conducting_body: 'IBPS / SBI',
    salary_range: '₹52,000 - ₹85,000',
    job_description: 'POs handle banking operations, customer service, sales, and branch management during probation.',
    key_skills: ['Finance', 'Communication', 'Sales', 'Customer Service', 'MS Office'],
    work_location: 'Pan India',
    job_nature: 'Office',
    growth_prospects: 'PO → Assistant Manager → Manager → Sr. Manager → Chief Manager → AGM → DGM → GM → ED → CMD',
    perks_benefits: 'DA, HRA, Medical, LTC, Pension (NPS), Staff loans at concessional rates',
    ai_risk_percentage: 55,
    competition_ratio: '1:200',
    exam_id: 'ibps-po',
    exam_name: 'IBPS PO Exam'
  },
  {
    id: 'bank-clerk',
    name: 'Bank Clerk',
    sector: 'Government',
    category: 'Banking',
    education: 'Graduate',
    age_limit: '20-28 years',
    selection_process: 'IBPS/SBI Clerk Exam (Prelims + Mains)',
    conducting_body: 'IBPS / SBI',
    salary_range: '₹29,000 - ₹55,000',
    job_description: 'Clerks handle day-to-day banking operations including cash handling, customer service, and data entry.',
    key_skills: ['Basic Banking Knowledge', 'Communication', 'Computer Skills', 'Accuracy'],
    work_location: 'State-wise postings',
    job_nature: 'Office',
    growth_prospects: 'Clerk → Senior Clerk → Special Assistant → Officer Grade (via promotion)',
    perks_benefits: 'DA, HRA, Medical, staff loans, pension (NPS)',
    ai_risk_percentage: 50,
    competition_ratio: '1:250',
    exam_id: 'ibps-clerk',
    exam_name: 'IBPS Clerk Exam'
  },
  {
    id: 'rbi-grade-b',
    name: 'RBI Grade B Officer',
    sector: 'Government',
    category: 'Banking',
    education: 'Graduate (min. 60% marks)',
    age_limit: '21-30 years',
    selection_process: 'RBI Grade B Exam (Phase 1 + Phase 2 + Interview)',
    conducting_body: 'RBI',
    salary_range: '₹77,208 - ₹1,30,000',
    job_description: 'Grade B officers handle monetary policy, economic analysis, regulation, and administration at the Reserve Bank.',
    key_skills: ['Economics', 'Finance', 'Banking Regulations', 'Research', 'Report Writing', 'Analytical Skills'],
    work_location: 'Mumbai / Delhi / Major Cities',
    job_nature: 'Office',
    growth_prospects: 'Grade B → Grade C → Grade D → Grade E → Grade F (ED/DG level)',
    perks_benefits: 'Subsidized quarters, pension, medical, LTC, children education allowance, high prestige',
    ai_risk_percentage: 40,
    competition_ratio: '1:600',
    exam_id: 'rbi-grade-b',
    exam_name: 'RBI Grade B Exam'
  },
  // Insurance
  {
    id: 'lic-aao',
    name: 'LIC AAO',
    sector: 'Government',
    category: 'Insurance',
    education: 'Graduate',
    age_limit: '21-30 years',
    selection_process: 'LIC AAO Exam (Prelims + Mains + Interview)',
    conducting_body: 'LIC',
    salary_range: '₹53,600 - ₹80,000',
    job_description: 'Assistant Administrative Officers handle life insurance operations, sales management, and administrative functions at LIC.',
    key_skills: ['Insurance Knowledge', 'Communication', 'Sales', 'Finance', 'MS Office'],
    work_location: 'Pan India',
    job_nature: 'Office',
    growth_prospects: 'AAO → AO → Manager → Senior Manager → Chief Manager → DM → GM',
    perks_benefits: 'Pension, medical, LTC, HRA, accommodation, staff benefits',
    ai_risk_percentage: 45,
    competition_ratio: '1:300',
    exam_id: 'lic-aao',
    exam_name: 'LIC AAO Exam'
  },
  // Education
  {
    id: 'govt-teacher',
    name: 'Government School Teacher',
    sector: 'Government',
    category: 'Education',
    education: 'Graduate + B.Ed (TGT) / D.El.Ed (PRT)',
    age_limit: '18-40 years',
    selection_process: 'CTET / TET + State Teacher Recruitment Exam',
    conducting_body: 'CTET / State TET',
    salary_range: '₹35,400 - ₹1,12,400',
    job_description: 'Teachers educate students in government schools, following curriculum and shaping young minds.',
    key_skills: ['Subject Knowledge', 'Teaching Methodology', 'Communication', 'Patience', 'Child Psychology'],
    work_location: 'State-specific (Rural/Urban)',
    job_nature: 'Teaching',
    growth_prospects: 'PRT → TGT → PGT → Vice Principal → Principal',
    perks_benefits: 'Pension, medical, summer/winter vacations, job security',
    ai_risk_percentage: 20,
    competition_ratio: '1:100',
    exam_id: 'ctet',
    exam_name: 'CTET'
  },
  {
    id: 'college-professor',
    name: 'College/University Professor',
    sector: 'Government',
    category: 'Education',
    education: 'Post Graduate + NET/SET; Ph.D preferred',
    age_limit: 'Below 40 years',
    selection_process: 'UGC NET + University Direct Recruitment / State PSC',
    conducting_body: 'UGC / Universities',
    salary_range: '₹57,700 - ₹1,82,400',
    job_description: 'Professors teach graduate/post-graduate students, conduct research, and contribute to academic knowledge.',
    key_skills: ['Advanced Subject Knowledge', 'Research', 'Writing', 'Critical Thinking', 'Mentoring'],
    work_location: 'Universities / Colleges Pan India',
    job_nature: 'Teaching + Research',
    growth_prospects: 'Assistant Professor → Associate Professor → Professor → HOD → Dean → Vice Chancellor',
    perks_benefits: 'Research grants, sabbatical, pension, quarters, high academic freedom',
    ai_risk_percentage: 25,
    competition_ratio: 'Varies by institution',
    exam_id: 'ugc-net',
    exam_name: 'UGC NET'
  },
  // Healthcare
  {
    id: 'govt-mbbs-doctor',
    name: 'Government Doctor (MBBS)',
    sector: 'Government',
    category: 'Healthcare',
    education: 'MBBS',
    age_limit: 'Below 35 years',
    selection_process: 'State PSC Health Services / UPSC CMS',
    conducting_body: 'State PSC / UPSC',
    salary_range: '₹56,100 - ₹2,00,000',
    job_description: 'Government doctors provide medical services at hospitals, PHCs, and CHCs, serving rural and urban populations.',
    key_skills: ['Medical Knowledge', 'Patient Care', 'Diagnosis', 'Emergency Management', 'Communication'],
    work_location: 'Rural / Urban Government Hospitals',
    job_nature: 'Clinical',
    growth_prospects: 'Medical Officer → Sr. Medical Officer → CMO → DCMO → CMO (District) → Director Health Services',
    perks_benefits: 'NPA (Non-Practising Allowance), quarters, pension, private practice permission (some states)',
    ai_risk_percentage: 42,
    competition_ratio: '1:40',
    exam_id: 'neet-ug',
    exam_name: 'NEET-UG'
  },
  {
    id: 'staff-nurse',
    name: 'Staff Nurse (Government)',
    sector: 'Government',
    category: 'Healthcare',
    education: 'B.Sc Nursing / GNM',
    age_limit: '18-35 years',
    selection_process: 'ESIC / AIIMS / State NHM / DSSSB Nurse Recruitment',
    conducting_body: 'Various',
    salary_range: '₹25,500 - ₹81,100',
    job_description: 'Nurses provide patient care, assist doctors, manage medical records, and ensure quality healthcare delivery.',
    key_skills: ['Patient Care', 'Medical Knowledge', 'Empathy', 'Teamwork', 'Record Keeping'],
    work_location: 'Government Hospitals / CHCs / PHCs',
    job_nature: 'Clinical',
    growth_prospects: 'Staff Nurse → Senior Staff Nurse → Nursing Sister → Matron → Chief Nursing Officer',
    perks_benefits: 'Pension, quarters, medical, uniform allowance',
    ai_risk_percentage: 30,
    competition_ratio: '1:50',
    exam_id: 'nursing-exam',
    exam_name: 'Nursing Recruitment Exam'
  },
  // Science & Technology
  {
    id: 'isro-scientist',
    name: 'ISRO Scientist/Engineer',
    sector: 'Government',
    category: 'Science & Technology',
    education: 'B.E./B.Tech / M.Sc (Physics, Maths)',
    age_limit: 'Below 35 years',
    selection_process: 'ISRO ICRB Written Test + Interview',
    conducting_body: 'ISRO',
    salary_range: '₹56,100 - ₹2,00,000',
    job_description: 'Scientists and engineers at ISRO work on space missions, satellite development, and aerospace research.',
    key_skills: ['Aerospace/Mechanical/Electronics Engineering', 'Programming', 'Research', 'Mathematics'],
    work_location: 'Bengaluru / Thiruvananthapuram / Ahmedabad / Sriharikota',
    job_nature: 'Research + Development',
    growth_prospects: 'Scientist/Engineer SC → SD → SE → SF → SG → Distinguished Scientist → Chairman',
    perks_benefits: 'Subsidized housing, medical, pension, research grants, prestige',
    ai_risk_percentage: 20,
    competition_ratio: '1:100',
    exam_id: 'isro-recruitment',
    exam_name: 'ISRO Recruitment'
  },
  {
    id: 'drdo-scientist',
    name: 'DRDO Scientist/Engineer',
    sector: 'Government',
    category: 'Defence R&D',
    education: 'B.E./B.Tech / M.Sc',
    age_limit: 'Below 28-35 years',
    selection_process: 'DRDO CEPTAM Written Test + Interview / GATE + Interview',
    conducting_body: 'DRDO',
    salary_range: '₹56,100 - ₹2,00,000',
    job_description: 'DRDO scientists develop defence technologies, weapons systems, and cutting-edge research for national security.',
    key_skills: ['Engineering', 'Research', 'Defence Technology', 'Testing & Evaluation'],
    work_location: 'Labs across India (Delhi, Pune, Hyderabad, Bengaluru)',
    job_nature: 'Research + Development',
    growth_prospects: 'Scientist B → C → D → E → F → G → Distinguished Scientist',
    perks_benefits: 'Government quarters, research grants, pension, prestige',
    ai_risk_percentage: 22,
    competition_ratio: '1:150',
    exam_id: 'drdo-ceptam',
    exam_name: 'DRDO CEPTAM'
  },
  // Judiciary
  {
    id: 'civil-judge',
    name: 'Civil Judge / Judicial Magistrate',
    sector: 'Government',
    category: 'Judiciary',
    education: 'LLB (3-year after Graduation / 5-year integrated)',
    age_limit: 'Below 35 years',
    selection_process: 'State PCS (J) Exam (Prelims + Mains + Viva Voce)',
    conducting_body: 'State PSC',
    salary_range: '₹77,840 - ₹2,08,700',
    job_description: 'Judicial magistrates handle criminal and civil cases, deliver judgments, and ensure justice delivery in courts.',
    key_skills: ['Law', 'Legal Reasoning', 'Constitutional Law', 'IPC', 'CrPC', 'CPC', 'Judgment Writing'],
    work_location: 'District Courts across the State',
    job_nature: 'Court + Office',
    growth_prospects: 'Civil Judge Jr. Division → Sr. Division → ADJ → DJ → High Court Judge → Supreme Court Judge',
    perks_benefits: 'Government accommodation, vehicle, pension, high prestige, no executive pressure',
    ai_risk_percentage: 15,
    competition_ratio: '1:500',
    exam_id: 'state-pcs-j',
    exam_name: 'State PCS (Judiciary)'
  },
  // Central Government Services
  {
    id: 'ssc-cgl',
    name: 'SSC CGL Officer',
    sector: 'Government',
    category: 'Central Services',
    education: 'Graduate',
    age_limit: '18-32 years',
    selection_process: 'SSC CGL (Tier 1 + Tier 2 + Document Verification)',
    conducting_body: 'SSC',
    salary_range: '₹25,500 - ₹1,00,000 (varies by post)',
    job_description: 'CGL officers work as Inspectors, Assistants, Auditors in various central government ministries and departments.',
    key_skills: ['General Awareness', 'Quantitative Aptitude', 'English', 'Reasoning', 'Computer Proficiency'],
    work_location: 'Pan India',
    job_nature: 'Office',
    growth_prospects: 'Post-specific promotions within respective departments',
    perks_benefits: 'DA, HRA, pension, job security, medical',
    ai_risk_percentage: 35,
    competition_ratio: '1:1,700',
    exam_id: 'ssc-cgl',
    exam_name: 'SSC CGL'
  },
  // PRIVATE SECTOR JOBS
  // IT Sector
  {
    id: 'software-engineer',
    name: 'Software Engineer',
    sector: 'Private',
    category: 'IT',
    education: 'B.E./B.Tech (CS/IT/ECE) / BCA + MCA',
    age_limit: 'No upper limit',
    selection_process: 'Campus Placement / Online Coding Tests + Technical Interview',
    conducting_body: 'Companies',
    salary_range: '₹4 LPA - ₹60 LPA',
    job_description: 'Software engineers design, develop, and maintain software applications and systems across various domains.',
    key_skills: ['Programming (Python/Java/C++/JS)', 'DSA', 'DBMS', 'OS', 'System Design', 'Problem Solving', 'Git'],
    work_location: 'Metro Cities / WFH options',
    job_nature: 'Desk',
    growth_prospects: 'Fresher → Software Engineer → Senior SE → Staff Engineer → Principal Engineer → Engineering Manager → VP Eng → CTO',
    perks_benefits: 'Health insurance, stock options (ESOPs), WFH flexibility, variable pay, cab, food',
    ai_risk_percentage: 78,
    competition_ratio: 'High',
    exam_id: null,
    exam_name: null
  },
  {
    id: 'full-stack-developer',
    name: 'Full Stack Developer',
    sector: 'Private',
    category: 'IT',
    education: 'B.Tech/BCA/B.Sc CS / Bootcamp Certificate',
    age_limit: 'No restriction',
    selection_process: 'Portfolio Review + Technical Interview',
    conducting_body: 'Companies / Freelance',
    salary_range: '₹3 LPA - ₹40 LPA',
    job_description: 'Full stack developers work on both frontend and backend of web applications, handling complete development cycles.',
    key_skills: ['HTML', 'CSS', 'JavaScript', 'React/Angular/Vue', 'Node.js/Django', 'SQL/NoSQL', 'Git'],
    work_location: 'Metro Cities / WFH',
    job_nature: 'Desk',
    growth_prospects: 'Junior Dev → Developer → Senior Dev → Tech Lead → Architect → CTO',
    perks_benefits: 'Flexible hours, remote work, learning tools, health insurance',
    ai_risk_percentage: 75,
    competition_ratio: 'Moderate',
    exam_id: null,
    exam_name: null
  },
  {
    id: 'data-scientist',
    name: 'Data Scientist / ML Engineer',
    sector: 'Private',
    category: 'IT/Data',
    education: 'B.E./B.Tech (CS/Stats/Math) / M.Sc',
    age_limit: 'No restriction',
    selection_process: 'Online Coding Test + ML Case Study + Technical Interview',
    conducting_body: 'Companies',
    salary_range: '₹8 LPA - ₹80 LPA',
    job_description: 'Data scientists analyze complex data, build ML models, and derive insights to solve business problems.',
    key_skills: ['Python', 'R', 'SQL', 'Machine Learning', 'Deep Learning', 'Statistics', 'TensorFlow/PyTorch'],
    work_location: 'Metro Cities / WFH',
    job_nature: 'Desk',
    growth_prospects: 'Junior DS → Data Scientist → Sr. DS → Lead DS → Data Science Manager → Head of AI/ML',
    perks_benefits: 'ESOPs, flexible hours, learning budget, health insurance, performance bonus',
    ai_risk_percentage: 65,
    competition_ratio: 'Moderate',
    exam_id: null,
    exam_name: null
  },
  {
    id: 'cybersecurity-analyst',
    name: 'Cybersecurity Analyst',
    sector: 'Private',
    category: 'IT/Security',
    education: 'B.E./B.Tech (CS/IT) + CEH/CISSP/OSCP preferred',
    age_limit: 'No restriction',
    selection_process: 'Technical Interview + Practical Security Assessment',
    conducting_body: 'Companies',
    salary_range: '₹5 LPA - ₹50 LPA',
    job_description: 'Cybersecurity analysts protect organizations from cyber threats, conduct security audits, and implement protection measures.',
    key_skills: ['Ethical Hacking', 'Network Security', 'VAPT', 'Python', 'Kali Linux', 'Cryptography', 'OWASP'],
    work_location: 'Metro Cities / Remote',
    job_nature: 'Desk',
    growth_prospects: 'Junior Analyst → Security Analyst → Senior Analyst → Security Architect → CISO',
    perks_benefits: 'Certifications sponsored, high demand, bonuses, flexible work',
    ai_risk_percentage: 30,
    competition_ratio: 'Low',
    exam_id: null,
    exam_name: null
  },
  {
    id: 'cloud-engineer',
    name: 'Cloud Engineer (AWS/Azure/GCP)',
    sector: 'Private',
    category: 'IT/Cloud',
    education: 'B.E./B.Tech + Cloud Certifications',
    age_limit: 'No restriction',
    selection_process: 'Technical Interview + Cloud Architecture Case Study',
    conducting_body: 'Companies',
    salary_range: '₹6 LPA - ₹60 LPA',
    job_description: 'Cloud engineers design, implement, and manage cloud infrastructure for organizations.',
    key_skills: ['AWS/Azure/GCP', 'Docker', 'Kubernetes', 'Terraform', 'Linux', 'Python', 'CI/CD'],
    work_location: 'Metro Cities / Remote',
    job_nature: 'Desk',
    growth_prospects: 'Cloud Engineer → Sr. Cloud Engineer → Cloud Architect → Principal Architect',
    perks_benefits: 'ESOPs, remote flexibility, learning credits, health insurance',
    ai_risk_percentage: 55,
    competition_ratio: 'Moderate',
    exam_id: null,
    exam_name: null
  },
  {
    id: 'product-manager',
    name: 'Product Manager',
    sector: 'Private',
    category: 'Tech/Business',
    education: 'Any Graduate (Engineering/MBA preferred)',
    age_limit: 'No restriction',
    selection_process: 'Aptitude Test + Case Study + PM Interview',
    conducting_body: 'Tech Companies',
    salary_range: '₹12 LPA - ₹80 LPA',
    job_description: 'Product managers define product strategy, roadmap, and work with engineering and design to build products.',
    key_skills: ['Product Thinking', 'Data Analysis', 'Communication', 'Agile/Scrum', 'SQL', 'User Research', 'Strategy'],
    work_location: 'Metro Cities / WFH',
    job_nature: 'Desk + Meetings',
    growth_prospects: 'Associate PM → PM → Senior PM → Group PM → Director of Product → VP Product → CPO',
    perks_benefits: 'ESOPs, high bonuses, leadership exposure, flexible work',
    ai_risk_percentage: 50,
    competition_ratio: 'High',
    exam_id: null,
    exam_name: null
  },
  // Engineering
  {
    id: 'civil-engineer-private',
    name: 'Civil Engineer (Private)',
    sector: 'Private',
    category: 'Engineering',
    education: 'B.E./B.Tech (Civil Engineering)',
    age_limit: '21-35 years',
    selection_process: 'Campus Placement / Written Test + Technical Interview',
    conducting_body: 'Companies',
    salary_range: '₹3 LPA - ₹25 LPA',
    job_description: 'Civil engineers design, construct, and maintain infrastructure projects like buildings, roads, bridges, and dams.',
    key_skills: ['AutoCAD', 'Structural Design', 'Construction Management', 'Estimation', 'IS Codes', 'MS Project'],
    work_location: 'Pan India (Site-based / Office)',
    job_nature: 'Site + Office',
    growth_prospects: 'Junior Engineer → Site Engineer → Project Engineer → Project Manager → General Manager',
    perks_benefits: 'Site allowances, health insurance, travel reimbursement',
    ai_risk_percentage: 48,
    competition_ratio: 'Moderate',
    exam_id: null,
    exam_name: null
  },
  {
    id: 'mechanical-engineer-private',
    name: 'Mechanical Engineer (Private)',
    sector: 'Private',
    category: 'Engineering',
    education: 'B.E./B.Tech (Mechanical Engineering)',
    age_limit: '21-35 years',
    selection_process: 'Campus Placement + Technical Interview',
    conducting_body: 'Companies',
    salary_range: '₹3 LPA - ₹25 LPA',
    job_description: 'Mechanical engineers work on design, manufacturing, and maintenance of mechanical systems.',
    key_skills: ['AutoCAD', 'SolidWorks/CATIA', 'Thermodynamics', 'Manufacturing Processes', 'Quality Control'],
    work_location: 'Industrial Cities (Pune, Chennai, Surat, Ahmedabad)',
    job_nature: 'Factory + Office',
    growth_prospects: 'Graduate Engineer → Engineer → Senior Engineer → Manager → GM',
    perks_benefits: 'Health insurance, performance bonus, shift allowance',
    ai_risk_percentage: 50,
    competition_ratio: 'Moderate',
    exam_id: null,
    exam_name: null
  },
  {
    id: 'electrical-engineer-private',
    name: 'Electrical Engineer (Private)',
    sector: 'Private',
    category: 'Engineering',
    education: 'B.E./B.Tech (Electrical Engineering)',
    age_limit: '21-35 years',
    selection_process: 'Campus Placement + Technical Interview',
    conducting_body: 'Companies',
    salary_range: '₹3 LPA - ₹22 LPA',
    job_description: 'Electrical engineers design, develop, and maintain electrical systems and equipment.',
    key_skills: ['AutoCAD Electrical', 'PLC/SCADA', 'Power Systems', 'Switchgear', 'Electrical Standards'],
    work_location: 'Industrial Belts / Metro Cities',
    job_nature: 'Factory + Office',
    growth_prospects: 'Junior EE → Engineer → Senior Engineer → Manager',
    perks_benefits: 'Health insurance, performance bonus, travel allowance',
    ai_risk_percentage: 52,
    competition_ratio: 'Moderate',
    exam_id: null,
    exam_name: null
  },
  // Healthcare
  {
    id: 'private-doctor',
    name: 'Private Hospital Doctor',
    sector: 'Private',
    category: 'Healthcare',
    education: 'MBBS (General) / MD/MS (Specialist)',
    age_limit: 'No restriction',
    selection_process: 'Degree verification + Hospital Interview',
    conducting_body: 'Hospitals',
    salary_range: '₹60,000 - ₹5,00,000+',
    job_description: 'Private doctors provide medical services at private hospitals, clinics, or run their own practice.',
    key_skills: ['Medical Expertise', 'Patient Communication', 'Clinical Skills', 'Emergency Handling', 'Empathy'],
    work_location: 'Private Hospitals across India',
    job_nature: 'Clinical',
    growth_prospects: 'Junior Doctor → Resident → Consultant → Senior Consultant → HOD',
    perks_benefits: 'High earning potential, professional prestige, clinic practice allowance',
    ai_risk_percentage: 38,
    competition_ratio: 'Moderate',
    exam_id: null,
    exam_name: null
  },
  {
    id: 'dentist',
    name: 'Dentist (Private Practice)',
    sector: 'Private',
    category: 'Healthcare',
    education: 'BDS (BDS) / MDS for specialization',
    age_limit: 'No restriction',
    selection_process: 'BDS/MDS degree + Dental Council Registration',
    conducting_body: 'Dental Council',
    salary_range: '₹30,000 - ₹2,00,000',
    job_description: 'Dentists provide oral healthcare, perform dental procedures, and educate patients on oral hygiene.',
    key_skills: ['Dental Surgery', 'Patient Management', 'Sterilization Protocols', 'Communication', 'Manual Dexterity'],
    work_location: 'Across India (own clinic or chain)',
    job_nature: 'Clinical',
    growth_prospects: 'Dentist → Specialist → Own Practice → Dental Clinic Chain Owner',
    perks_benefits: 'High earning potential with own practice, independent profession',
    ai_risk_percentage: 45,
    competition_ratio: 'Moderate',
    exam_id: null,
    exam_name: null
  },
  {
    id: 'pharmacist',
    name: 'Pharmacist (Private)',
    sector: 'Private',
    category: 'Healthcare',
    education: 'B.Pharm / D.Pharm',
    age_limit: '18-35 years',
    selection_process: 'Pharmacy Council Registration + Interview',
    conducting_body: 'Pharmacy Council',
    salary_range: '₹15,000 - ₹60,000',
    job_description: 'Pharmacists dispense medications, counsel patients, and manage pharmacy operations.',
    key_skills: ['Pharmacology', 'Drug Interaction Knowledge', 'Customer Communication', 'Inventory Management'],
    work_location: 'Across India',
    job_nature: 'Retail/Hospital',
    growth_prospects: 'Pharmacist → Senior Pharmacist → Pharmacy Manager → Area Manager',
    perks_benefits: 'Health benefits, annual increment, career in pharmaceutical companies',
    ai_risk_percentage: 55,
    competition_ratio: 'Low',
    exam_id: null,
    exam_name: null
  },
  // Finance
  {
    id: 'chartered-accountant',
    name: 'Chartered Accountant (CA)',
    sector: 'Private',
    category: 'Finance',
    education: 'CA (ICAI) — Foundation → Intermediate → Final + Articleship',
    age_limit: 'No restriction',
    selection_process: 'ICAI CA Foundation → Intermediate → Final Exam + 3-year Articleship',
    conducting_body: 'ICAI',
    salary_range: '₹6 LPA - ₹1 Crore+',
    job_description: 'CAs handle accounting, auditing, taxation, and financial advisory for companies and individuals.',
    key_skills: ['Accounting (IndAS/IFRS)', 'Taxation (Direct/Indirect)', 'Audit', 'Financial Analysis', 'Tally/SAP'],
    work_location: 'Pan India (Big4 / Industry / Practice)',
    job_nature: 'Desk',
    growth_prospects: 'Article Assistant → CA Fresher → Senior Associate → Manager → Partner (Big4) / Own Practice',
    perks_benefits: 'High earning, Big4 perks, performance bonus, professional prestige',
    ai_risk_percentage: 85,
    competition_ratio: 'High',
    exam_id: 'ca-exam',
    exam_name: 'CA Exam (ICAI)'
  },
  {
    id: 'company-secretary',
    name: 'Company Secretary (CS)',
    sector: 'Private',
    category: 'Legal',
    education: 'CS (ICSI) — Foundation → Executive → Professional',
    age_limit: 'No restriction',
    selection_process: 'ICSI Exam (Foundation → Executive → Professional) + Practical Training',
    conducting_body: 'ICSI',
    salary_range: '₹4 LPA - ₹40 LPA',
    job_description: 'CS professionals handle corporate compliance, company law, SEBI regulations, and secretarial functions.',
    key_skills: ['Corporate Law', 'Companies Act 2013', 'SEBI Regulations', 'ROC Filings', 'Legal Drafting'],
    work_location: 'Pan India (Corporates / Law Firms)',
    job_nature: 'Desk',
    growth_prospects: 'CS Trainee → CS Executive → CS Manager → VP Compliance → Company Secretary (whole-time)',
    perks_benefits: 'Bonuses, health insurance, company car (senior level), professional prestige',
    ai_risk_percentage: 70,
    competition_ratio: 'Moderate',
    exam_id: 'cs-exam',
    exam_name: 'CS Exam (ICSI)'
  },
  {
    id: 'investment-banker',
    name: 'Investment Banker',
    sector: 'Private',
    category: 'Finance',
    education: 'MBA Finance / CA / CFA / B.Tech + MBA (IIM/IIT)',
    age_limit: 'No restriction',
    selection_process: 'Aptitude Test + Finance Case Study + Stress Interview',
    conducting_body: 'Investment Banks',
    salary_range: '₹8 LPA - ₹1 Crore+',
    job_description: 'Investment bankers advise on M&A, capital raising, and financial restructuring for corporations.',
    key_skills: ['Financial Modelling', 'DCF Valuation', 'Excel', 'Bloomberg', 'Communication', 'Deal Structuring'],
    work_location: 'Mumbai / Delhi NCR',
    job_nature: 'Desk',
    growth_prospects: 'Analyst → Associate → Vice President → Director → Managing Director',
    perks_benefits: 'Very high bonuses (up to 100% of salary), ESOPs, global exposure',
    ai_risk_percentage: 60,
    competition_ratio: 'Very High',
    exam_id: null,
    exam_name: null
  },
  {
    id: 'stock-trader',
    name: 'Stock Market Trader / Equity Research Analyst',
    sector: 'Private',
    category: 'Finance',
    education: 'MBA Finance / CFA / CA / B.Com + NISM',
    age_limit: 'No restriction',
    selection_process: 'NISM Certification + Company Interview / Self-employment',
    conducting_body: 'NISM / SEBI',
    salary_range: '₹4 LPA - Unlimited (own trading)',
    job_description: 'Traders and analysts study markets, analyze stocks, and execute trades for institutions or themselves.',
    key_skills: ['Technical & Fundamental Analysis', 'Bloomberg/Reuters', 'Excel', 'Risk Management', 'Finance'],
    work_location: 'Mumbai / Delhi NCR / Remote',
    job_nature: 'Desk',
    growth_prospects: 'Junior Analyst → Research Analyst → Sr. Analyst → Fund Manager → CIO',
    perks_benefits: 'High performance bonuses, flexible hours (for independent traders)',
    ai_risk_percentage: 72,
    competition_ratio: 'Varies',
    exam_id: null,
    exam_name: null
  },
  // Legal
  {
    id: 'advocate',
    name: 'Advocate / Lawyer (Private)',
    sector: 'Private',
    category: 'Legal',
    education: 'LLB (3-year / 5-year integrated)',
    age_limit: 'No restriction',
    selection_process: 'Bar Council of India enrolment + Registration',
    conducting_body: 'Bar Council',
    salary_range: '₹15,000 - ₹10 Lakh+/month',
    job_description: 'Lawyers represent clients in courts, provide legal advice, draft documents, and handle cases.',
    key_skills: ['Legal Research', 'Drafting', 'Oratory', 'Criminal/Civil/Corporate Law', 'Negotiation'],
    work_location: 'Pan India',
    job_nature: 'Court + Office',
    growth_prospects: 'Junior Advocate → Senior Advocate → Partner (Law Firm) → Senior Advocate (HC/SC)',
    perks_benefits: 'Self-determined income, professional prestige, independent practice',
    ai_risk_percentage: 72,
    competition_ratio: 'Very High',
    exam_id: null,
    exam_name: null
  },
  // Aviation
  {
    id: 'commercial-pilot',
    name: 'Commercial Pilot',
    sector: 'Private',
    category: 'Aviation',
    education: '12th PCM; CPL from DGCA-approved institute',
    age_limit: '17-60 years',
    selection_process: 'DGCA Written Exams + Flying Hours (200 hrs min) + Airline Interview + Type Rating',
    conducting_body: 'DGCA',
    salary_range: '₹1,50,000 - ₹6,00,000+',
    job_description: 'Commercial pilots fly aircraft for airlines, transporting passengers and cargo safely.',
    key_skills: ['Aviation Technology', 'Navigation', 'Meteorology', 'Communication', 'Decision Making', 'CRM'],
    work_location: 'Major Airports across India',
    job_nature: 'Flying + Ground',
    growth_prospects: 'First Officer (Co-Pilot) → Senior First Officer → Captain → Senior Captain → Chief Pilot',
    perks_benefits: 'Free travel perks, layover allowances, health benefits, high salary, uniform',
    ai_risk_percentage: 25,
    competition_ratio: 'High',
    exam_id: 'dgca-cpl',
    exam_name: 'DGCA CPL'
  },
  // Architecture
  {
    id: 'architect',
    name: 'Architect (Private)',
    sector: 'Private',
    category: 'Design',
    education: 'B.Arch + COA Registration',
    age_limit: 'No restriction',
    selection_process: 'Portfolio Review + Technical Interview + COA Registration',
    conducting_body: 'COA',
    salary_range: '₹3.5 LPA - ₹30 LPA',
    job_description: 'Architects design buildings and spaces, balancing aesthetics, functionality, and sustainability.',
    key_skills: ['AutoCAD', 'Revit', 'SketchUp', 'Structural Basics', '3D Rendering', 'Creativity', 'Project Management'],
    work_location: 'Pan India (Urban areas)',
    job_nature: 'Studio + Site',
    growth_prospects: 'Junior Architect → Architect → Senior Architect → Principal Architect → Own Firm',
    perks_benefits: 'Creative freedom, project-based bonuses, high earning with own firm',
    ai_risk_percentage: 55,
    competition_ratio: 'Moderate',
    exam_id: null,
    exam_name: null
  },
  // Media
  {
    id: 'journalist',
    name: 'Journalist / Reporter',
    sector: 'Private',
    category: 'Media',
    education: 'BA/MA Journalism / Mass Communication / BJMC',
    age_limit: 'No restriction',
    selection_process: 'Aptitude + Interview + Portfolio / Writing Test',
    conducting_body: 'Media Houses',
    salary_range: '₹2.5 LPA - ₹25 LPA',
    job_description: 'Journalists investigate stories, write articles, conduct interviews, and present news to the public.',
    key_skills: ['Writing', 'Research', 'Communication', 'Video Editing', 'Source Building', 'Objectivity'],
    work_location: 'Metro Cities',
    job_nature: 'Field + Office',
    growth_prospects: 'Trainee Reporter → Reporter → Sr. Reporter → Editor → Sr. Editor → Editor-in-Chief',
    perks_benefits: 'Travel allowance, press credentials, national exposure, byline recognition',
    ai_risk_percentage: 65,
    competition_ratio: 'High',
    exam_id: null,
    exam_name: null
  },
  // Marketing
  {
    id: 'marketing-manager',
    name: 'Marketing Manager',
    sector: 'Private',
    category: 'Business',
    education: 'Any Graduate / MBA Marketing',
    age_limit: 'No restriction',
    selection_process: 'Aptitude + Marketing Case Study + Campaign Portfolio + Interview',
    conducting_body: 'Companies',
    salary_range: '₹3 LPA - ₹35 LPA',
    job_description: 'Marketing managers develop and execute marketing strategies to promote products and brand awareness.',
    key_skills: ['SEO', 'SEM', 'Social Media', 'Content Marketing', 'Google Analytics', 'Meta Ads', 'Email Marketing', 'CRM'],
    work_location: 'Pan India / Remote',
    job_nature: 'Desk + Events',
    growth_prospects: 'Marketing Executive → Sr. Executive → Marketing Manager → Marketing Head → CMO',
    perks_benefits: 'Performance bonuses, travel for events, flexible hours (digital roles)',
    ai_risk_percentage: 58,
    competition_ratio: 'Moderate',
    exam_id: null,
    exam_name: null
  },
  // HR
  {
    id: 'hr-manager',
    name: 'HR Manager',
    sector: 'Private',
    category: 'Business',
    education: 'MBA HR / MA HRM / BBA HR',
    age_limit: 'No restriction',
    selection_process: 'HR Case Study + Competency-Based Interview',
    conducting_body: 'Companies',
    salary_range: '₹3 LPA - ₹30 LPA',
    job_description: 'HR managers handle recruitment, employee relations, training, and organizational development.',
    key_skills: ['Talent Acquisition', 'Labor Laws', 'MS Office', 'HRIS Tools (SAP/Workday)', 'Communication', 'Empathy'],
    work_location: 'Pan India',
    job_nature: 'Desk',
    growth_prospects: 'HR Executive → Sr. HR Executive → HR Manager → Sr. HR Manager → CHRO',
    perks_benefits: 'Health insurance, bonuses, professional memberships',
    ai_risk_percentage: 52,
    competition_ratio: 'Moderate',
    exam_id: null,
    exam_name: null
  },
  // Supply Chain
  {
    id: 'supply-chain-manager',
    name: 'Supply Chain / Logistics Manager',
    sector: 'Private',
    category: 'Operations',
    education: 'B.E. (Mechanical/IE) / MBA Operations / BBA',
    age_limit: 'No restriction',
    selection_process: 'Technical Interview + Operations Case Study',
    conducting_body: 'Companies',
    salary_range: '₹4 LPA - ₹35 LPA',
    job_description: 'Supply chain managers optimize the flow of goods, from suppliers to customers.',
    key_skills: ['ERP (SAP/Oracle)', 'Inventory Management', 'Vendor Management', 'Logistics', 'Data Analysis'],
    work_location: 'Industrial Cities / Ports / Warehouses',
    job_nature: 'Operations',
    growth_prospects: 'Executive → Sr. Executive → Manager → Sr. Manager → VP Supply Chain → COO',
    perks_benefits: 'Travel allowance, performance bonus, health insurance',
    ai_risk_percentage: 45,
    competition_ratio: 'Low',
    exam_id: null,
    exam_name: null
  },
  // Creative
  {
    id: 'fashion-designer',
    name: 'Fashion Designer',
    sector: 'Private',
    category: 'Creative',
    education: 'B.Des (Fashion Design) from NIFT/NID/Pearl',
    age_limit: 'No restriction',
    selection_process: 'Portfolio Submission + Design Challenge + Interview',
    conducting_body: 'Fashion Houses',
    salary_range: '₹2.5 LPA - ₹25 LPA',
    job_description: 'Fashion designers create clothing, accessories, and footwear, staying ahead of trends.',
    key_skills: ['Sketching', 'Pattern Making', 'Textile Knowledge', 'Colour Theory', 'CAD (CLO 3D)', 'Trend Forecasting'],
    work_location: 'Mumbai / Delhi / Bengaluru',
    job_nature: 'Studio + Factory',
    growth_prospects: 'Design Assistant → Junior Designer → Designer → Senior Designer → Creative Director',
    perks_benefits: 'Fashion shows, international exposure, high creative freedom',
    ai_risk_percentage: 60,
    competition_ratio: 'High',
    exam_id: null,
    exam_name: null
  },
  {
    id: 'ui-ux-designer',
    name: 'UI/UX Designer',
    sector: 'Private',
    category: 'Creative/Tech',
    education: 'B.Des / BFA / Bootcamp certificate',
    age_limit: 'No restriction',
    selection_process: 'Portfolio Review + Design Assignment + Tool Proficiency Test',
    conducting_body: 'Tech Companies',
    salary_range: '₹2.5 LPA - ₹25 LPA',
    job_description: 'UI/UX designers create intuitive, visually appealing digital interfaces and experiences.',
    key_skills: ['Adobe Creative Suite', 'Figma', 'Sketch', 'UI/UX Principles', 'Typography', 'Branding'],
    work_location: 'Pan India / Remote / Freelance',
    job_nature: 'Desk',
    growth_prospects: 'Junior Designer → Designer → Senior Designer → Lead Designer → Design Manager → Head of Design',
    perks_benefits: 'Flexible hours, remote work, creative freedom, freelance income',
    ai_risk_percentage: 58,
    competition_ratio: 'Moderate',
    exam_id: null,
    exam_name: null
  },
  // Creator Economy
  {
    id: 'content-creator',
    name: 'Content Creator / YouTuber / Influencer',
    sector: 'Private',
    category: 'Creator Economy',
    education: 'No formal degree required',
    age_limit: 'No restriction',
    selection_process: 'Self-built audience through consistent content',
    conducting_body: 'Self-driven',
    salary_range: '₹0 - ₹5 Crore+',
    job_description: 'Content creators produce videos, posts, and content to build audiences and monetize through brand deals.',
    key_skills: ['Video Production', 'Scriptwriting', 'SEO', 'Social Media', 'Personal Branding', 'Editing'],
    work_location: 'Anywhere (Remote / Studio)',
    job_nature: 'Flexible',
    growth_prospects: 'Nano → Micro → Macro → Mega Influencer / Channel Growth',
    perks_benefits: 'Complete creative freedom, travel sponsorships, product collaborations, no ceiling on income',
    ai_risk_percentage: 50,
    competition_ratio: 'Very High',
    exam_id: null,
    exam_name: null
  },
  // Hospitality
  {
    id: 'chef',
    name: 'Chef / Culinary Expert',
    sector: 'Private',
    category: 'Hospitality',
    education: 'Diploma in Hotel Management / B.Sc HM / Culinary Arts Certification',
    age_limit: 'No restriction',
    selection_process: 'Culinary Test + Interview / Hotel Management Exam',
    conducting_body: 'Hotels / Restaurants',
    salary_range: '₹2 LPA - ₹30 LPA',
    job_description: 'Chefs prepare food, design menus, manage kitchens, and ensure food quality and hygiene.',
    key_skills: ['Culinary Skills', 'Menu Planning', 'Inventory Management', 'Kitchen Safety', 'Creativity', 'Teamwork'],
    work_location: 'Hotels / Restaurants / Cloud Kitchens Pan India',
    job_nature: 'Kitchen',
    growth_prospects: 'Commis Chef → Demi Chef → Chef de Partie → Sous Chef → Head Chef → Executive Chef',
    perks_benefits: 'Free meals, hotel accommodation (luxury properties), tips, creative freedom',
    ai_risk_percentage: 40,
    competition_ratio: 'Moderate',
    exam_id: null,
    exam_name: null
  },
  // Entrepreneurship
  {
    id: 'entrepreneur',
    name: 'Entrepreneur / Startup Founder',
    sector: 'Private',
    category: 'Business',
    education: 'No formal requirement',
    age_limit: 'No restriction',
    selection_process: 'Business idea + Investor Pitch + Market Validation',
    conducting_body: 'Self / Investors',
    salary_range: '₹0 - Unlimited',
    job_description: 'Entrepreneurs identify opportunities, build products, and scale companies from idea to execution.',
    key_skills: ['Business Strategy', 'Financial Planning', 'Leadership', 'Sales', 'Marketing', 'Product', 'Resilience', 'Networking'],
    work_location: 'Bengaluru / Delhi NCR / Mumbai / Hyderabad / Pune',
    job_nature: 'All-encompassing',
    growth_prospects: 'Idea Stage → MVP → Seed Stage → Series A/B/C → IPO / Acquisition',
    perks_benefits: 'Unlimited income potential, equity in own company, freedom, legacy creation',
    ai_risk_percentage: 90,
    competition_ratio: 'Everyone',
    exam_id: null,
    exam_name: null
  },
  {
    id: 'business-owner',
    name: 'Business Owner / Trader / SME',
    sector: 'Private',
    category: 'Business',
    education: 'Basic financial literacy',
    age_limit: 'No restriction',
    selection_process: 'No formal exam',
    conducting_body: 'Self',
    salary_range: '₹0 - Unlimited',
    job_description: 'Business owners run retail, wholesale, or trading businesses, managing inventory, customers, and finances.',
    key_skills: ['Business Acumen', 'Financial Management', 'Customer Handling', 'Negotiation', 'Inventory', 'Local Market Knowledge'],
    work_location: 'Tier 1 / Tier 2 / Tier 3 cities',
    job_nature: 'Business Operations',
    growth_prospects: 'Small Retailer → Wholesale Dealer → Distributor → Regional Franchisee → National Chain',
    perks_benefits: 'Independence, scalable income, family legacy, no boss',
    ai_risk_percentage: 70,
    competition_ratio: 'Everyone',
    exam_id: null,
    exam_name: null
  }
]

export default careersData
